version: '2.4'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    networks:
      - libralink_network

networks:
  libralink_network:
    driver: bridge

volumes:
  vol_postgres:
