version: '2.4'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    networks:
      - libralink_network

  libralink-agent:
    image: libralink-agent
    container_name: libralink-agent
    ports:
      - "8082:8082"
    environment:
      DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/admin?currentSchema=public'
      DATASOURCE_USERNAME: 'admin'
      DATASOURCE_PASSWORD: 'admin'
    build:
      context: ./libralink-apps/suite
      dockerfile: Dockerfile
    networks:
      - libralink_network

networks:
  libralink_network:
    driver: bridge

volumes:
  vol_postgres:
